// <autogenerated>
//   This file was generated by dddappp code generator.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

module sui_crowdfunding_example::donation_refunded {

    use sui::object;
    use sui_crowdfunding_example::project::{Self, DonationRefunded};

    public fun id(donation_refunded: &DonationRefunded): object::ID {
        project::donation_refunded_id(donation_refunded)
    }

}
