// <autogenerated>
//   This file was generated by dddappp code generator.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

module sui_crowdfunding_example::project_aggregate {
    use std::string::String;
    use sui::balance::Balance;
    use sui::clock::Clock;
    use sui::sui::SUI;
    use sui::tx_context;
    use sui_crowdfunding_example::platform::Platform;
    use sui_crowdfunding_example::project;
    use sui_crowdfunding_example::project_create_logic;
    use sui_crowdfunding_example::project_donate_logic;
    use sui_crowdfunding_example::project_refund_logic;
    use sui_crowdfunding_example::project_start_logic;
    use sui_crowdfunding_example::project_update_logic;
    use sui_crowdfunding_example::project_withdraw_logic;

    public entry fun create(
        platform: &mut Platform,
        title: String,
        description: String,
        target: u64,
        deadline: u64,
        image: String,
        ctx: &mut tx_context::TxContext,
    ) {
        let project_created = project_create_logic::verify(
            platform,
            title,
            description,
            target,
            deadline,
            image,
            ctx,
        );
        let project = project_create_logic::mutate(
            &project_created,
            platform,
            ctx,
        );
        project::set_project_created_id(&mut project_created, project::id(&project));
        project::transfer_object(project, tx_context::sender(ctx));
        project::emit_project_created(project_created);
    }

    public entry fun update(
        project: project::Project,
        title: String,
        description: String,
        target: u64,
        image: String,
        ctx: &mut tx_context::TxContext,
    ) {
        let project_updated = project_update_logic::verify(
            title,
            description,
            target,
            image,
            &project,
            ctx,
        );
        let updated_project = project_update_logic::mutate(
            &project_updated,
            project,
            ctx,
        );
        project::update_version_and_transfer_object(updated_project, tx_context::sender(ctx));
        project::emit_project_updated(project_updated);
    }

    public entry fun start(
        project: project::Project,
        clock: &Clock,
        ctx: &mut tx_context::TxContext,
    ) {
        let project_started = project_start_logic::verify(
            clock,
            &project,
            ctx,
        );
        let updated_project = project_start_logic::mutate(
            &project_started,
            project,
            ctx,
        );
        project::update_version_and_share_object(updated_project);
        project::emit_project_started(project_started);
    }

    public fun donate(
        project: &mut project::Project,
        amount: Balance<SUI>,
        clock: &Clock,
        ctx: &mut tx_context::TxContext,
    ) {
        let donation_received = project_donate_logic::verify(
            &amount,
            clock,
            project,
            ctx,
        );
        project_donate_logic::mutate(
            &donation_received,
            amount,
            project,
            ctx,
        );
        project::update_object_version(project);
        project::emit_donation_received(donation_received);
    }

    public fun withdraw(
        project: &mut project::Project,
        clock: &Clock,
        ctx: &mut tx_context::TxContext,
    ): Balance<SUI> {
        let vault_withdrawn = project_withdraw_logic::verify(
            clock,
            project,
            ctx,
        );
        let withdraw_return = project_withdraw_logic::mutate(
            &vault_withdrawn,
            project,
            ctx,
        );
        project::update_object_version(project);
        project::emit_vault_withdrawn(vault_withdrawn);
        withdraw_return
    }

    public fun refund(
        project: &mut project::Project,
        clock: &Clock,
        ctx: &mut tx_context::TxContext,
    ): Balance<SUI> {
        let donation_refunded = project_refund_logic::verify(
            clock,
            project,
            ctx,
        );
        let refund_return = project_refund_logic::mutate(
            &donation_refunded,
            project,
            ctx,
        );
        project::update_object_version(project);
        project::emit_donation_refunded(donation_refunded);
        refund_return
    }

}
